CREATE USER 'wordpress'@'172.16.50.%' IDENTIFIED BY 'wordpress_password';
GRANT USAGE ON *.* TO 'wordpress'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `wordpress`;
GRANT ALL PRIVILEGES ON `wordpress`.* TO 'wordpress'@'%'; 

CREATE USER 'lychee'@'172.16.50.%' IDENTIFIED BY 'lychee_password';
GRANT USAGE ON *.* TO 'lychee'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `lychee`;
GRANT ALL PRIVILEGES ON `lychee`.* TO 'lychee'@'%'; 